apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alert-manager-pvc
  namespace: monitoring
spec:
  storageClassName: alert-manager-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
